### ISSUE TITLE
Calibration Crash (Linux v0.6.20)

### ISSUE THREAD

**Issue by willhuffman** [pupil-labs/pyuvc#12]
Crashes after calibration in most recent release.  The terminal log is as follows:

```
Starting Calibration

Stopping Calibration
Process Process-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/home/name/Programs/pupil/pupil_src/capture/world.py", line 408, in world
    g_pool.gui.update()
  File "pyglui/ui.pyx", line 136, in pyglui.ui.UI.update (pyglui/ui.c:7741)
  File "pyglui/ui.pyx", line 104, in pyglui.ui.UI.handle_input (pyglui/ui.c:7265)
  File "pyglui/menus.pxi", line 198, in pyglui.ui.Stretching_Menu.handle_input (pyglui/ui.c:33534)
  File "pyglui/menus.pxi", line 202, in pyglui.ui.Stretching_Menu.handle_input (pyglui/ui.c:33388)
  File "pyglui/ui_elements.pxi", line 902, in pyglui.ui.Thumb.handle_input (pyglui/ui.c:27905)
  File "pyglui/ui_elements.pxi", line 924, in pyglui.ui.Thumb.handle_input (pyglui/ui.c:27480)
  File "pyglui/ui.pyx", line 299, in pyglui.ui.Synced_Value.value.__set__ (pyglui/ui.c:42472)
  File "/home/name/Programs/pupil/pupil_src/shared_modules/calibration_routines/natural_features_calibration.py", line 71, in toggle
    self.stop()
  File "/home/name/Programs/pupil/pupil_src/shared_modules/calibration_routines/natural_features_calibration.py", line 91, in stop
    if self.g_pool.binocular:
AttributeError: 'Global_Container' object has no attribute 'binocular'
```

**Comment by cpicanco** [comment]
1) are you running form source?
2) have you the most recent version of pyglui?
3) do you need to run in binocular mode?

**Comment by willhuffman** [comment]
Problem solved by updating pyglui.  Some other issues with compiling Pupil tho.  Closing this issue and relocating.  Thanks!
