### ISSUE TITLE
Cannot install last version of pyuvc on Linux Mint 18 with Python 3.5

### ISSUE THREAD

**Issue by mtee** [pupil-labs/pyuvc#27]
I have installed the specified fork of libuvc and libjpeg-turbo-1.5.1, however, when I try to run
sudo -H pip3 install git+https://github.com/pupil-labs/pyuvc

I get
```
Collecting git+https://github.com/pupil-labs/pyuvc
  Cloning https://github.com/pupil-labs/pyuvc to /tmp/pip-gacfscrv-build
Installing collected packages: uvc
  Running setup.py install for uvc ... error
    Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-gacfscrv-build/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-xpii6a94-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_ext
    building 'uvc' extension
    creating build
    creating build/temp.linux-x86_64-3.5
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/lib/python3/dist-packages/numpy/core/include -I/usr/include/python3.5m -c uvc.c -o build/temp.linux-x86_64-3.5/uvc.o
    In file included from /usr/lib/python3/dist-packages/numpy/core/include/numpy/ndarraytypes.h:1777:0,
                     from /usr/lib/python3/dist-packages/numpy/core/include/numpy/ndarrayobject.h:18,
                     from /usr/lib/python3/dist-packages/numpy/core/include/numpy/arrayobject.h:4,
                     from uvc.c:461:
    /usr/lib/python3/dist-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:15:2: warning: #warning "Using deprecated NumPy API, disable it by " "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
     #warning "Using deprecated NumPy API, disable it by " \
      ^
    uvc.c: In function ‘__pyx_f_3uvc_7Capture__enumerate_controls’:
    uvc.c:16709:26: warning: assignment discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
       __pyx_v_input_terminal = uvc_get_input_terminals(__pyx_v_self->devh);
                              ^
    uvc.c:16718:27: warning: assignment discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
       __pyx_v_output_terminal = uvc_get_output_terminals(__pyx_v_self->devh);
                               ^
    uvc.c:16727:27: warning: assignment discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
       __pyx_v_processing_unit = uvc_get_processing_units(__pyx_v_self->devh);
                               ^
    uvc.c:16736:26: warning: assignment discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
       __pyx_v_extension_unit = uvc_get_extension_units(__pyx_v_self->devh);
                              ^
    uvc.c: In function ‘__pyx_f_3uvc_7Capture__enumerate_formats’:
    uvc.c:17374:23: warning: assignment discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
       __pyx_v_format_desc = uvc_get_format_descs(__pyx_v_self->devh);
                           ^
    uvc.c: At top level:
    uvc.c:19728:13: warning: ‘__pyx_f_3uvc_on_status_update’ defined but not used [-Wunused-function]
     static void __pyx_f_3uvc_on_status_update(CYTHON_UNUSED enum uvc_status_class __pyx_v_status_class, CYTHON_UNUSED int __pyx_v_event, CYTHON_UNUSED int __pyx_v_selector, CYTHON_UNUSED enum uvc_status_attribute __pyx_v_status_attribute, CYTHON_UNUSED void *__pyx_v_data, CYTHON_UNUSED size_t __pyx_v_data_len, CYTHON_UNUSED void *__pyx_v_user_ptr) {
                 ^
    creating build/lib.linux-x86_64-3.5
    x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-Bsymbolic-functions -Wl,-z,relro -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 build/temp.linux-x86_64-3.5/uvc.o -lrt -luvc -lturbojpeg -o build/lib.linux-x86_64-3.5/uvc.cpython-35m-x86_64-linux-gnu.so
    /usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libturbojpeg.a(libturbojpeg_la-turbojpeg.o): relocation R_X86_64_32 against `.data' can not be used when making a shared object; recompile with -fPIC
    /usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libturbojpeg.a: error adding symbols: Bad value
    collect2: error: ld returned 1 exit status
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    
    ----------------------------------------
Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-gacfscrv-build/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-xpii6a94-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-gacfscrv-build/
You are using pip version 8.1.1, however version 9.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```
Also I noticed it uses the pip from python2 (which has version 8.1.1) instead of pip3, which is up-to-date: 
pip3 --version
pip 9.0.1 from /home/<user>/.local/lib/python3.5/site-packages (python 3.5)

**Comment by mkassner** [comment]
Hi I just updated the install instructions. Could you try again?

https://github.com/pupil-labs/pyuvc/blob/master/README.md

**Comment by mtee** [comment]
Hi, thanks, sadly still having the same error message when trying to install over pip. If I just run sudo python3 setup.py install in the cloned repo, the setup completes without the libturbojpeg error.

But pip install fails for both pyuvc and pyndsi libraries with the same error regarding libturbojpeg.
Here is the verbose output of sudo /usr/bin/python3 -m pip install --upgrade -v git+https://github.com/pupil-labs/pyuvc

```
The directory '/home/linuxuser/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/linuxuser/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting git+https://github.com/pupil-labs/pyuvc
  Cloning https://github.com/pupil-labs/pyuvc to /tmp/pip-e9ku06de-build
  Running command git clone -q https://github.com/pupil-labs/pyuvc /tmp/pip-e9ku06de-build
  Running setup.py (path:/tmp/pip-e9ku06de-build/setup.py) egg_info for package from git+https://github.com/pupil-labs/pyuvc
    Running command python setup.py egg_info
    Compiling uvc.pyx because it changed.
    [1/1] Cythonizing uvc.pyx
    running egg_info
    creating pip-egg-info/uvc.egg-info
    writing top-level names to pip-egg-info/uvc.egg-info/top_level.txt
    writing dependency_links to pip-egg-info/uvc.egg-info/dependency_links.txt
    writing pip-egg-info/uvc.egg-info/PKG-INFO
    writing manifest file 'pip-egg-info/uvc.egg-info/SOURCES.txt'
    warning: manifest_maker: standard file '-c' not found

    reading manifest file 'pip-egg-info/uvc.egg-info/SOURCES.txt'
    writing manifest file 'pip-egg-info/uvc.egg-info/SOURCES.txt'
  Source in /tmp/pip-e9ku06de-build has version 0.91, which satisfies requirement uvc==0.91 from git+https://github.com/pupil-labs/pyuvc
Installing collected packages: uvc
  Found existing installation: uvc 0.8
    DEPRECATION: Uninstalling a distutils installed project (uvc) has been deprecated and will be removed in a future version. This is due to the fact that uninstalling a distutils project will only partially uninstall the project.
    Uninstalling uvc-0.8:
      Removing file or directory /usr/local/lib/python3.5/dist-packages/uvc-0.8.egg-info
      Successfully uninstalled uvc-0.8
  Running setup.py install for uvc ...     Running command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-e9ku06de-build/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-t7y08zxd-record/install-record.txt --single-version-externally-managed --compile
    running install
    running build
    running build_ext
    building 'uvc' extension
    creating build
    creating build/temp.linux-x86_64-3.5
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/local/lib/python3.5/dist-packages/numpy/core/include -I/usr/include/python3.5m -c uvc.c -o build/temp.linux-x86_64-3.5/uvc.o
    In file included from /usr/local/lib/python3.5/dist-packages/numpy/core/include/numpy/ndarraytypes.h:1781:0,
                     from /usr/local/lib/python3.5/dist-packages/numpy/core/include/numpy/ndarrayobject.h:18,
                     from /usr/local/lib/python3.5/dist-packages/numpy/core/include/numpy/arrayobject.h:4,
                     from uvc.c:461:
    /usr/local/lib/python3.5/dist-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:15:2: warning: #warning "Using deprecated NumPy API, disable it by " "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
     #warning "Using deprecated NumPy API, disable it by " \
      ^
    uvc.c: In function ‘__pyx_f_3uvc_7Capture__enumerate_controls’:
    uvc.c:16709:26: warning: assignment discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
       __pyx_v_input_terminal = uvc_get_input_terminals(__pyx_v_self->devh);
                              ^
    uvc.c:16718:27: warning: assignment discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
       __pyx_v_output_terminal = uvc_get_output_terminals(__pyx_v_self->devh);
                               ^
    uvc.c:16727:27: warning: assignment discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
       __pyx_v_processing_unit = uvc_get_processing_units(__pyx_v_self->devh);
                               ^
    uvc.c:16736:26: warning: assignment discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
       __pyx_v_extension_unit = uvc_get_extension_units(__pyx_v_self->devh);
                              ^
    uvc.c: In function ‘__pyx_f_3uvc_7Capture__enumerate_formats’:
    uvc.c:17374:23: warning: assignment discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
       __pyx_v_format_desc = uvc_get_format_descs(__pyx_v_self->devh);
                           ^
    uvc.c: At top level:
    uvc.c:19728:13: warning: ‘__pyx_f_3uvc_on_status_update’ defined but not used [-Wunused-function]
     static void __pyx_f_3uvc_on_status_update(CYTHON_UNUSED enum uvc_status_class __pyx_v_status_class, CYTHON_UNUSED int __pyx_v_event, CYTHON_UNUSED int __pyx_v_selector, CYTHON_UNUSED enum uvc_status_attribute __pyx_v_status_attribute, CYTHON_UNUSED void *__pyx_v_data, CYTHON_UNUSED size_t __pyx_v_data_len, CYTHON_UNUSED void *__pyx_v_user_ptr) {
                 ^
    creating build/lib.linux-x86_64-3.5
    x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-Bsymbolic-functions -Wl,-z,relro -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 build/temp.linux-x86_64-3.5/uvc.o -lrt -luvc -lturbojpeg -o build/lib.linux-x86_64-3.5/uvc.cpython-35m-x86_64-linux-gnu.so
    /usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libturbojpeg.a(libturbojpeg_la-turbojpeg.o): relocation R_X86_64_32 against `.data' can not be used when making a shared object; recompile with -fPIC
    /usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libturbojpeg.a: error adding symbols: Bad value
    collect2: error: ld returned 1 exit status
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
error
  Rolling back uninstall of uvc
  Replacing /usr/local/lib/python3.5/dist-packages/uvc-0.8.egg-info
Cleaning up...
  Removing source in /tmp/pip-e9ku06de-build
Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-e9ku06de-build/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-t7y08zxd-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-e9ku06de-build/
Exception information:
Traceback (most recent call last):
  File "/home/linuxuser/.local/lib/python3.5/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/home/linuxuser/.local/lib/python3.5/site-packages/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/home/linuxuser/.local/lib/python3.5/site-packages/pip/req/req_set.py", line 784, in install
    **kwargs
  File "/home/linuxuser/.local/lib/python3.5/site-packages/pip/req/req_install.py", line 878, in install
    spinner=spinner,
  File "/home/linuxuser/.local/lib/python3.5/site-packages/pip/utils/__init__.py", line 707, in call_subprocess
    % (command_desc, proc.returncode, cwd))
pip.exceptions.InstallationError: Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-e9ku06de-build/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-t7y08zxd-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-e9ku06de-build/
```

**Comment by mkassner** [comment]
Hi for some reason its using a static lib when it should use a dynamic one (.so instead of .a)

can you try removing libuvc.a?

**Comment by mtee** [comment]
I had purged everything libturbojpeg from /usr/* and installed the lib again and now the installation works over pip. I suppose something got corrupted when I installed the 1.5.1 version over the previous one (1.4.3, I think). Thank you.

**Comment by mkassner** [comment]
Great!
