### ISSUE TITLE
Exception: Could not grab frame. Giving up. c920

### ISSUE THREAD

**Issue by cpicanco** [pupil-labs/pyuvc#4]
```
[{'device_address': 3, 'name': 'HD Pro Webcam C920', 'idVendor': 1133, 'serialNumber': 'ED3E505F', 'bus_number': 2, 'idProduct': 2093, 'uid': '2:3', 'manufacturer': 'unknown'}]
DEBUG:uvc:Found device that mached uid:'2:3'
DEBUG:uvc:Device '2:3' opended.
DEBUG:uvc:avaible video modes: [{'rates': [30, 24, 20, 15, 10, 7, 5], 'size': (640, 480)}, {'rates': [30, 24, 20, 15, 10, 7, 5], 'size': (160, 90)}, {'rates': [30, 24, 20, 15, 10, 7, 5], 'size': (160, 120)}, {'rates': [30, 24, 20, 15, 10, 7, 5], 'size': (176, 144)}, {'rates': [30, 24, 20, 15, 10, 7, 5], 'size': (320, 180)}, {'rates': [30, 24, 20, 15, 10, 7, 5], 'size': (320, 240)}, {'rates': [30, 24, 20, 15, 10, 7, 5], 'size': (352, 288)}, {'rates': [30, 24, 20, 15, 10, 7, 5], 'size': (432, 240)}, {'rates': [30, 24, 20, 15, 10, 7, 5], 'size': (640, 360)}, {'rates': [30, 24, 20, 15, 10, 7, 5], 'size': (800, 448)}, {'rates': [30, 24, 20, 15, 10, 7, 5], 'size': (800, 600)}, {'rates': [30, 24, 20, 15, 10, 7, 5], 'size': (864, 480)}, {'rates': [30, 24, 20, 15, 10, 7, 5], 'size': (960, 720)}, {'rates': [30, 24, 20, 15, 10, 7, 5], 'size': (1024, 576)}, {'rates': [30, 24, 20, 15, 10, 7, 5], 'size': (1280, 720)}, {'rates': [30, 24, 20, 15, 10, 7, 5], 'size': (1600, 896)}, {'rates': [30, 24, 20, 15, 10, 7, 5], 'size': (1920, 1080)}]
DEBUG:uvc:Adding "Auto Exposure Mode" control.
DEBUG:uvc:Adding "Auto Exposure Priority" control.
DEBUG:uvc:Adding "Absolute Exposure Time" control.
DEBUG:uvc:Adding "Auto Focus" control.
DEBUG:uvc:Adding "Absolute Focus" control.
DEBUG:uvc:Adding "Zoom absolute control" control.
DEBUG:uvc:Adding "Pan control" control.
DEBUG:uvc:Adding "Tilt control" control.
DEBUG:uvc:Adding "Backlight Compensation" control.
DEBUG:uvc:Adding "Brightness" control.
DEBUG:uvc:Adding "Contrast" control.
DEBUG:uvc:Adding "Gain" control.
DEBUG:uvc:Adding "Power Line frequency" control.
DEBUG:uvc:Adding "Saturation" control.
DEBUG:uvc:Adding "Sharpness" control.
DEBUG:uvc:Adding "White Balance temperature" control.
DEBUG:uvc:Adding "White Balance temperature,Auto" control.
8
1
250
1
0
100
0
0
0
128
128
0
2
128
128
4000
1
HD Pro Webcam C920
Capture device
	 device_address:3
	 name:HD Pro Webcam C920
	 idVendor:1133
	 serialNumber:ED3E505F
	 bus_number:2
	 idProduct:2093
	 uid:2:3
	 manufacturer:unknown
Estimated / selected altsetting bandwith : 309 / 384. 
DEBUG:uvc:Stream start.
DEBUG:uvc:Could not get Frame. Error: "Operation timed out.". Tried 0 times.
DEBUG:uvc:Could not get Frame. Error: "JPEG header corrupted.". Tried 1 times.
DEBUG:uvc:Could not get Frame. Error: "JPEG header corrupted.". Tried 2 times.
DEBUG:uvc:Could not get Frame. Error: "JPEG header corrupted.". Tried 3 times.
WARNING:uvc:Could not grab frame. Restarting device
DEBUG:uvc:Stream stopped
DEBUG:uvc:Stream closed
DEBUG:uvc:Stream stop.
Estimated / selected altsetting bandwith : 309 / 384. 
DEBUG:uvc:Stream start.
DEBUG:uvc:Could not get Frame. Error: "Operation timed out.". Tried 0 times.
DEBUG:uvc:Could not get Frame. Error: "JPEG header corrupted.". Tried 1 times.
DEBUG:uvc:Could not get Frame. Error: "JPEG header corrupted.". Tried 2 times.
DEBUG:uvc:Could not get Frame. Error: "JPEG header corrupted.". Tried 3 times.
WARNING:uvc:Could not grab frame. Restarting device
DEBUG:uvc:Stream stopped
DEBUG:uvc:Stream closed
DEBUG:uvc:Stream stop.
Estimated / selected altsetting bandwith : 309 / 384. 
DEBUG:uvc:Stream start.
Traceback (most recent call last):
  File "/home/rafael/git/pyuvc/example.py", line 23, in <module>
    frame = cap.get_frame_robust()
  File "uvc.pyx", line 500, in uvc.Capture.get_frame_robust (uvc.c:13114)
    raise Exception("Could not grab frame. Giving up.")
Exception: Could not grab frame. Giving up.
ERROR:uvc:Can't stop stream: Error:'Operation timed out.'. Will ignore this and try to continue.
DEBUG:uvc:Stream closed
DEBUG:uvc:Stream stop.
DEBUG:uvc:UVC device closed.
```

**Comment by mkassner** [comment]
hi,

there us a bandwidth factor you can supply on init. Please set it to 1 and see if that fixes it.

**Comment by cpicanco** [comment]
bandwith goes to:
```
Estimated / selected altsetting bandwith : 160 / 192.
```
error persists

**Comment by cpicanco** [comment]
seems related to #5

**Comment by mkassner** [comment]
sorry, I meant set it to 2 or 3

**Comment by ckemere** [comment]
For people that find this issue in the future, I found that I needed to set the bandwidth_factor=4 for my logitech webcam to work. It seems that the reported bandwidth for the logitech is quite close to the proper value?
