### ISSUE TITLE
Exception: Could not grab frame. Giving up. c270

### ISSUE THREAD

**Issue by cpicanco** [pupil-labs/pyuvc#5]
```
[{'device_address': 5, 'name': 'unknown', 'idVendor': 1133, 'serialNumber': '1CEAC320', 'bus_number': 1, 'idProduct': 2085, 'uid': '1:5', 'manufacturer': 'unknown'}]
DEBUG:uvc:Found device that mached uid:'1:5'
DEBUG:uvc:Device '1:5' opended.
DEBUG:uvc:avaible video modes: [{'rates': [30, 25, 20, 15, 10, 5], 'size': (640, 480)}, {'rates': [30, 25, 20, 15, 10, 5], 'size': (160, 120)}, {'rates': [30, 25, 20, 15, 10, 5], 'size': (176, 144)}, {'rates': [30, 25, 20, 15, 10, 5], 'size': (320, 176)}, {'rates': [30, 25, 20, 15, 10, 5], 'size': (320, 240)}, {'rates': [30, 25, 20, 15, 10, 5], 'size': (352, 288)}, {'rates': [30, 25, 20, 15, 10, 5], 'size': (432, 240)}, {'rates': [30, 25, 20, 15, 10, 5], 'size': (544, 288)}, {'rates': [30, 25, 20, 15, 10, 5], 'size': (640, 360)}, {'rates': [30, 25, 20, 15, 10, 5], 'size': (752, 416)}, {'rates': [30, 25, 20, 15, 10, 5], 'size': (800, 448)}, {'rates': [30, 25, 20, 15, 10, 5], 'size': (800, 600)}, {'rates': [30, 25, 20, 15, 10, 5], 'size': (864, 480)}, {'rates': [30, 25, 20, 15, 10, 5], 'size': (960, 544)}, {'rates': [30, 25, 20, 15, 10, 5], 'size': (960, 720)}, {'rates': [30, 25, 20, 15, 10, 5], 'size': (1024, 576)}, {'rates': [30, 25, 20, 15, 10, 5], 'size': (1184, 656)}, {'rates': [30, 25, 20, 15, 10, 5], 'size': (1280, 720)}, {'rates': [30, 25, 20, 15, 10, 5], 'size': (1280, 960)}]
DEBUG:uvc:Adding "Auto Exposure Mode" control.
DEBUG:uvc:Adding "Auto Exposure Priority" control.
DEBUG:uvc:Adding "Absolute Exposure Time" control.
DEBUG:uvc:Adding "Backlight Compensation" control.
DEBUG:uvc:Adding "Brightness" control.
DEBUG:uvc:Adding "Contrast" control.
DEBUG:uvc:Adding "Gain" control.
DEBUG:uvc:Adding "Power Line frequency" control.
DEBUG:uvc:Adding "Saturation" control.
DEBUG:uvc:Adding "Sharpness" control.
DEBUG:uvc:Adding "White Balance temperature" control.
DEBUG:uvc:Adding "White Balance temperature,Auto" control.
8
1
166
1
128
32
0
2
32
24
4000
1
unknown
Capture device
	 device_address:5
	 name:unknown
	 idVendor:1133
	 serialNumber:1CEAC320
	 bus_number:1
	 idProduct:2085
	 uid:1:5
	 manufacturer:unknown
Estimated / selected altsetting bandwith : 309 / 384. 
DEBUG:uvc:Stream start.
DEBUG:uvc:Could not get Frame. Error: "Operation timed out.". Tried 0 times.
DEBUG:uvc:Could not get Frame. Error: "Operation timed out.". Tried 1 times.
DEBUG:uvc:Could not get Frame. Error: "Operation timed out.". Tried 2 times.
DEBUG:uvc:Could not get Frame. Error: "Operation timed out.". Tried 3 times.
WARNING:uvc:Could not grab frame. Restarting device
DEBUG:uvc:Stream stopped
DEBUG:uvc:Stream closed
DEBUG:uvc:Stream stop.
Estimated / selected altsetting bandwith : 309 / 384. 
DEBUG:uvc:Stream start.
DEBUG:uvc:Could not get Frame. Error: "Operation timed out.". Tried 0 times.
DEBUG:uvc:Could not get Frame. Error: "Operation timed out.". Tried 1 times.
DEBUG:uvc:Could not get Frame. Error: "Operation timed out.". Tried 2 times.
DEBUG:uvc:Could not get Frame. Error: "Operation timed out.". Tried 3 times.
WARNING:uvc:Could not grab frame. Restarting device
DEBUG:uvc:Stream stopped
DEBUG:uvc:Stream closed
DEBUG:uvc:Stream stop.
Estimated / selected altsetting bandwith : 309 / 384. 
DEBUG:uvc:Stream start.
Traceback (most recent call last):
  File "/home/rafael/git/pyuvc/example.py", line 23, in <module>
    frame = cap.get_frame_robust()
  File "uvc.pyx", line 500, in uvc.Capture.get_frame_robust (uvc.c:13114)
    raise Exception("Could not grab frame. Giving up.")
Exception: Could not grab frame. Giving up.
DEBUG:uvc:Stream stopped
DEBUG:uvc:Stream closed
DEBUG:uvc:Stream stop.
DEBUG:uvc:UVC device closed.
```

**Comment by mkassner** [comment]
hi,

there us a bandwidth factor you can supply on init. Please set it to 1 and see if that fixes it.
