### ISSUE TITLE
Exception: Can't get stream control: Error:'Mode not supported.' VX-800

### ISSUE THREAD

**Issue by cpicanco** [pupil-labs/pyuvc#7]
```
[{'device_address': 10, 'name': 'Microsoft LifeCam VX-800', 'idVendor': 1118, 'serialNumber': 'unknown', 'bus_number': 1, 'idProduct': 1894, 'uid': '1:10', 'manufacturer': 'Microsoft'}]
DEBUG:uvc:Found device that mached uid:'1:10'
DEBUG:uvc:Device '1:10' opended.
DEBUG:uvc:avaible video modes: []
DEBUG:uvc:Adding "Auto Exposure Mode" control.
DEBUG:uvc:Adding "Absolute Exposure Time" control.
DEBUG:uvc:Adding "Backlight Compensation" control.
DEBUG:uvc:Adding "Brightness" control.
DEBUG:uvc:Adding "Contrast" control.
DEBUG:uvc:Adding "Gain" control.
DEBUG:uvc:Adding "Power Line frequency" control.
DEBUG:uvc:Adding "Hue" control.
DEBUG:uvc:Adding "Saturation" control.
DEBUG:uvc:Adding "Sharpness" control.
DEBUG:uvc:Adding "Gamma" control.
DEBUG:uvc:Adding "White Balance temperature" control.
DEBUG:uvc:Adding "White Balance temperature,Auto" control.
8
116
1
2
10
34
2
0
4
0
130
6500
1
Microsoft LifeCam VX-800
Capture device
	 device_address:10
	 name:Microsoft LifeCam VX-800
	 idVendor:1118
	 serialNumber:unknown
	 bus_number:1
	 idProduct:1894
	 uid:1:10
	 manufacturer:Microsoft
Traceback (most recent call last):
  File "/home/rafael/git/pyuvc/example.py", line 23, in <module>
    frame = cap.get_frame_robust()
  File "uvc.pyx", line 493, in uvc.Capture.get_frame_robust (uvc.c:12932)
    frame = self.get_frame()
  File "uvc.pyx", line 508, in uvc.Capture.get_frame (uvc.c:13216)
    self._start()
  File "uvc.pyx", line 464, in uvc.Capture._start (uvc.c:12435)
    self._configure_stream()
  File "uvc.pyx", line 456, in uvc.Capture._configure_stream (uvc.c:12340)
    raise Exception("Can't get stream control: Error:'%s'."%uvc_error_codes[status])
Exception: Can't get stream control: Error:'Mode not supported.'.
DEBUG:uvc:UVC device closed.
```

**Comment by mkassner** [comment]
hmm I m not sure what the issue. Is I dont have this hardware. Does pyv4l2 work?
