### ISSUE TITLE
File "uvc.pyx", line 544: The uvc. uvc_stream_open_ctrl Error.

### ISSUE THREAD

**Issue by 962557346** [pupil-labs/pyuvc#75]
Hello,

I've met the error on Windows 10 64-bit, when I tried to run the `pyuvc`  example code with my Integrated Webcam on the computer. This is what I get:

```python
import uvc
import logging
import cv2
logging.basicConfig(level=logging.INFO)
dev_list = uvc.device_list()
print(dev_list)
cap1 = uvc.Capture(dev_list[0]["uid"])
Output:
[{'name': 'unknown', 'manufacturer': 'unknown', 'serialNumber': 'unknown', 'idProduct': 11146, 'idVendor': 7119, 'device_address': 4, 'bus_number': 1, 'uid': '1:4'}]
Traceback (most recent call last):
  File "F:/pyuvc/uvc_example.py", line 12, in <module>
    cap1 = uvc.Capture(dev_list[0]["uid"])
  File "uvc.pyx", line 455, in uvc.Capture.__init__
  File "uvc.pyx", line 507, in uvc.Capture._init_device
uvc.OpenError
```

I have also tried install libusbK to replace the composite parent in the Zadig. I get some device information. But I also failed. This is what I get:

```python
from __future__ import print_function
import uvc
import logging
import cv2
logging.basicConfig(level=logging.INFO)

dev_list = uvc.device_list()
print(dev_list)
cap1 = uvc.Capture(dev_list[0]["uid"])

print(cap1.avaible_modes)
for x in range(10):
    print(x)
    cap1.frame_mode = (1280, 720, 30)
    for x in range(100):
        frame2 = cap1.get_frame_robust()
        print(frame2.img.shape)
        cv2.imshow("img2", frame2.gray)
        cv2.waitKey(1)
cap = None

[{'name': 'Integrated_Webcam_HD', 'manufacturer': 'CNFDH73M4160178A2D52', 'serialNumber': 'unknown', 'idProduct': 11146, 'idVendor': 7119, 'device_address': 4, 'bus_number': 1, 'uid': '1:4'}]
[(848, 480, 30), (960, 540, 30), (1280, 720, 30)]
0
Traceback (most recent call last):
  File "F:/pyuvc/uvc_example.py", line 27, in <module>
    frame2 = cap1.get_frame_robust()
  File "uvc.pyx", line 572, in uvc.Capture.get_frame_robust
  File "uvc.pyx", line 588, in uvc.Capture.get_frame
  File "uvc.pyx", line 544, in uvc.Capture._start
uvc.InitError
```
The line 544 code:
```
status = uvc.uvc_stream_open_ctrl(self.devh, &self.strmh, &self.ctrl)
 if status != uvc.UVC_SUCCESS:
        raise InitError("Can't open stream control: Error:'%s'."%uvc_error_codes[status])
```
I have tried to run the Pupil Integrated Camera, which can work successfully.

Can you help me? Looking forward to your reply.

**Comment by 962557346** [comment]
I have worked with DirectShow. It only need one line:
cv::VideoCapture cap(0, cv::CAP_DSHOW);
