### ISSUE TITLE
Exception: Can't get stream control: Error:'Mode not supported.'. USB 2.0 Camera

### ISSUE THREAD

**Issue by cpicanco** [pupil-labs/pyuvc#8]
```
[{'device_address': 4, 'name': 'USB 2.0 Camera', 'idVendor': 1266, 'serialNumber': 'SN0001', 'bus_number': 2, 'idProduct': 45537, 'uid': '2:4', 'manufacturer': 'Chicony Electronics Co., Ltd.'}]
DEBUG:uvc:Found device that mached uid:'2:4'
DEBUG:uvc:Device '2:4' opended.
DEBUG:uvc:avaible video modes: []
DEBUG:uvc:Adding "Auto Exposure Priority" control.
DEBUG:uvc:Adding "Backlight Compensation" control.
DEBUG:uvc:Adding "Brightness" control.
DEBUG:uvc:Adding "Contrast" control.
DEBUG:uvc:Adding "Power Line frequency" control.
DEBUG:uvc:Adding "Hue" control.
DEBUG:uvc:Adding "Saturation" control.
DEBUG:uvc:Adding "Sharpness" control.
DEBUG:uvc:Adding "Gamma" control.
1
1
18
20
2
0
28
3
100
USB 2.0 Camera
Capture device
	 device_address:4
	 name:USB 2.0 Camera
	 idVendor:1266
	 serialNumber:SN0001
	 bus_number:2
	 idProduct:45537
	 uid:2:4
	 manufacturer:Chicony Electronics Co., Ltd.
Traceback (most recent call last):
  File "/home/rafael/git/pyuvc/example.py", line 23, in <module>
    frame = cap.get_frame_robust()
  File "uvc.pyx", line 493, in uvc.Capture.get_frame_robust (uvc.c:12932)
    frame = self.get_frame()
  File "uvc.pyx", line 508, in uvc.Capture.get_frame (uvc.c:13216)
    self._start()
  File "uvc.pyx", line 464, in uvc.Capture._start (uvc.c:12435)
    self._configure_stream()
  File "uvc.pyx", line 456, in uvc.Capture._configure_stream (uvc.c:12340)
    raise Exception("Can't get stream control: Error:'%s'."%uvc_error_codes[status])
Exception: Can't get stream control: Error:'Mode not supported.'.
DEBUG:uvc:UVC device closed.
```

**Comment by mkassner** [comment]
Please make sure this camera can do mjpeg image transfer..
