### ISSUE TITLE
uvc_bindings.InitError: Can't start isochronous stream: Error:'Mode not supported'.

### ISSUE THREAD

**Issue by ErfolgreichCharismatisch** [pupil-labs/pyuvc#96]
I am iterating through different modes on my raspberry pi with

```
for mode in cap.available_modes:
    was = f"{cap.name} running at {mode}"
```

and I get the frame in a loop:

```
frame = cap.get_frame_robust() 
fd.write(frame.jpeg_buffer)
```

Now when going to higher resolutions and framerates, even though the supported boolean is set, I get 

```
Traceback (most recent call last):
  File "/home/pi/display/testLibUVC.py", line 42, in <module>
    frame = cap.get_frame_robust()
            ^^^^^^^^^^^^^^^^^^^^^^
  File "uvc_bindings.pyx", line 675, in uvc_bindings.Capture.get_frame_robust
  File "uvc_bindings.pyx", line 689, in uvc_bindings.Capture.get_frame
  File "uvc_bindings.pyx", line 651, in uvc_bindings.Capture._start
uvc_bindings.InitError: Can't start isochronous stream: Error:'Mode not supported'.
```

For lower res it works. Where's the bottleneck?

**Comment by Kamizzs** [comment]
I am doing the same thing with a USB Microscope and I get the same error even with lower resolution.

However, it works when I use an older firmware for the USB Microscope. It's a Smart G-Scope and the version that was working with is the 1.4.2, the one that didn't work is the 1.5.5.

**Comment by yurikleb** [comment]
I have the same problem on a Raspberry Pi 5. 
All works well in lower resolutions, but when I try to select a full-HD mode, I get the same error above:
`uvc_bindings.InitError: Can't start isochronous stream: Error:'Mode not supported'.`
